let Item : Type = {
  title : Text,
  subtitle : Text,
  arg : Text
}

let makeItem : ({title : Text, subtitle : Text, arg : Text }) -> Item = \(args: {title : Text, subtitle : Text, arg : Text}) ->
  let item : Item =
  {
    title = args.title,
    subtitle = args.subtitle,
    arg = args.arg
  }
  in item

let services : List Item =
  [
    makeItem { title = "ACM Private CA", subtitle = "", arg = "https://console.aws.amazon.com/acm-pca/home"},
    makeItem { title = "API Gateway", subtitle = "Amazon API Gateway makes it easy to create, maintain, monitor, and secure APIs at any scale.", arg = "https://console.aws.amazon.com/apigateway/home"},
    makeItem { title = "AWS Amplify", subtitle = "AWS Amplify is a complete platform for mobile and web app development that scales with your business. Sophisticated cloud-powered features made easy. No servers to manage.", arg = "https://console.aws.amazon.com/amplify/home"},
    makeItem { title = "AWS App Mesh", subtitle = "AWS App Mesh makes it easy to monitor and control microservices running on AWS.", arg = "https://console.aws.amazon.com/appmesh/home"},
    makeItem { title = "AWS AppConfig", subtitle = "Deploy application configuration changes to your applications in a validated, monitored and controlled way.", arg = "https://console.aws.amazon.com/systems-manager/appconfig/home"},
    makeItem { title = "AWS AppSync", subtitle = "Real-time data sync using GraphQL for mobile & web apps, available online and offline. Share data across devices and users.", arg = "https://console.aws.amazon.com/appsync/home"},
    makeItem { title = "AWS Auto Scaling", subtitle = "AWS Auto Scaling maintains steady application performance by automating the scaling of multiple application resources for your applications.", arg = "https://console.aws.amazon.com/awsautoscaling/home"},
    makeItem { title = "AWS Backup", subtitle = "AWS Backup is a fully managed backup service that makes it easy to centralize and automate the back up of data across AWS services in the cloud as well as on-premises.", arg = "https://console.aws.amazon.com/backup/home"},
    makeItem { title = "AWS Budgets", subtitle = "AWS Budgets lets you set custom cost and usage budgets that alert you when you exceed your budgeted thresholds.", arg = "https://console.aws.amazon.com/billing/home#/budgets#/home"},
    makeItem { title = "AWS Chatbot", subtitle = "AWS Chatbot is an interactive agent for monitoring and using AWS from chat rooms.", arg = "https://console.aws.amazon.com/chatbot/home"},
    makeItem { title = "AWS Cloud Map", subtitle = "Define friendly names for your cloud resources so that your applications can quickly and dynamically discover them.", arg = "https://console.aws.amazon.com/cloudmap/home"},
    makeItem { title = "AWS Compute Optimizer", subtitle = "AWS Compute Optimizer recommends optimal AWS Compute resources to reduce costs and improve performance for your workloads.", arg = "https://console.aws.amazon.com/compute-optimizer/home"},
    makeItem { title = "AWS Cost Explorer", subtitle = "", arg = "https://console.aws.amazon.com/cost-reports/home"},
    makeItem { title = "AWS Cost Explorer", subtitle = "AWS Cost Explorer lets you dive deeper into your cost and usage data to identify trends, pinpoint cost drivers, and detect anomalies.", arg = "https://console.aws.amazon.com/cost-management/home"},
    makeItem { title = "AWS Data Exchange", subtitle = "Easily exchange data in the cloud. Millions of AWS customers can now find, subscribe to, and use more than 700 data products from dozens of qualified data providers.", arg = "https://console.aws.amazon.com/dataexchange/home"},
    makeItem { title = "AWS DeepComposer", subtitle = "AWS DeepComposer gives developers a creative way to get started with machine learning. Get hands-on, with a musical keyboard and the latest machine learning techniques, designed to expand your ML skills.", arg = "https://console.aws.amazon.com/deepcomposer/home"},
    makeItem { title = "AWS DeepLens", subtitle = "Grow machine learning skills through hands-on computer vision tutorials and pre-built models.", arg = "https://console.aws.amazon.com/deeplens/home"},
    makeItem { title = "AWS DeepRacer", subtitle = "The fastest way to get rolling with machine learning with an autonomous 1/18th scale race car, 3D driving simulator, and global racing league", arg = "https://console.aws.amazon.com/deepracer/home"},
    makeItem { title = "AWS Firewall Manager", subtitle = "Centrally configure and manage firewall rules across accounts and applications", arg = "https://console.aws.amazon.com/wafv2/home"},
    makeItem { title = "AWS Glue", subtitle = "AWS Glue is a fully managed ETL (extract, transform, and load) service that makes it simple and cost-effective to categorize your data, clean it, enrich it and move it reliably between various data stores.", arg = "https://console.aws.amazon.com/glue/home"},
    makeItem { title = "AWS IQ", subtitle = "Complete projects faster with help from third-party AWS Certified experts", arg = "https://console.aws.amazon.comhttps://iq.aws.amazon.com/?utm=csl"},
    makeItem { title = "AWS Lake Formation", subtitle = "AWS Lake Formation makes it easy to set up your secure data lake, accelerating the time spent making data available for analysis and machine learning.", arg = "https://console.aws.amazon.com/lakeformation/home"},
    makeItem { title = "AWS License Manager", subtitle = "With AWS License Manager you can set customized rules, manage centrally, and discover software, across accounts, whether you’re running on AWS, on premises, or a public cloud. ", arg = "https://console.aws.amazon.com/license-manager/home"},
    makeItem { title = "AWS Marketplace Subscriptions", subtitle = "Digital catalog where you can find, buy, and deploy software", arg = "https://console.aws.amazon.com/marketplace/home"},
    makeItem { title = "AWS Migration Hub", subtitle = "Simplify and accelerate the migration of your data centers to AWS with a single location to track application migrations.", arg = "https://console.aws.amazon.com/migrationhub/home"},
    makeItem { title = "AWS Organizations", subtitle = "AWS Organizations helps you centrally govern your environment as you grow and scale your workloads across your AWS accounts.", arg = "https://console.aws.amazon.com/organizations/home"},
    makeItem { title = "AWS Outposts", subtitle = "Run AWS Services On Premises", arg = "https://console.aws.amazon.com/outposts/home"},
    makeItem { title = "AWS RoboMaker", subtitle = "AWS RoboMaker makes it easy to develop, test, and deploy robotics applications, as well as build intelligent robotics functions using cloud services.", arg = "https://console.aws.amazon.com/robomaker/home"},
    makeItem { title = "AWS Single Sign-On", subtitle = "Cloud single sign-on (SSO) service that makes it easy to manage SSO access to multiple AWS accounts and business applications.", arg = "https://console.aws.amazon.com/singlesignon/home"},
    makeItem { title = "AWS Transfer Family", subtitle = "AWS Transfer for SFTP is a secure file transfer service that stores your data in Amazon S3 and simplifies the migration of SFTP workflows to AWS.", arg = "https://console.aws.amazon.com/transfer/home"},
    makeItem { title = "AWS Well-Architected Tool", subtitle = "Review your workloads with AWS Well-Architected Tool and get AWS best practice guidance for designing and operating workloads in the cloud.", arg = "https://console.aws.amazon.com/wellarchitected/home"},
    makeItem { title = "Access Analyzer", subtitle = "", arg = "https://console.aws.amazon.com/access-analyzer/home"},
    makeItem { title = "Alexa for Business", subtitle = "Empower your organization with Alexa; access the tools you need to manage Alexa devices, skills, and users, and an API to build custom skills.", arg = "https://console.aws.amazon.com/a4b/home"},
    makeItem { title = "Amazon AppFlow", subtitle = "Amazon AppFlow is an application integration service that enables you to create bidirectional data flows between SaaS apps and AWS in just a few clicks.", arg = "https://console.aws.amazon.com/appflow/home"},
    makeItem { title = "Amazon Augmented AI", subtitle = "Amazon A2I brings human review to all developers, removing the undifferentiated heavy lifting associated with building human review systems or managing large numbers of human reviewers.", arg = "https://console.aws.amazon.com/a2i/home"},
    makeItem { title = "Amazon Braket", subtitle = "Fully managed service that enables scientists, researchers, and developers to explore, evaluate and experiment with quantum computing.", arg = "https://console.aws.amazon.comhttps://pages.awscloud.com/Amazon-Braket-Preview.html"},
    makeItem { title = "Amazon Chime", subtitle = "Amazon Chime is a communications service that transforms online meetings and video conferencing, making them easier and more secure.", arg = "https://console.aws.amazon.comhttps://chime.aws.amazon.com"},
    makeItem { title = "Amazon CodeGuru", subtitle = "Get intelligent recommendations, based on machine learning, for building and running modern applications. Improve code quality and application performance.", arg = "https://console.aws.amazon.com/codeguru/home"},
    makeItem { title = "Amazon Comprehend", subtitle = "Amazon Comprehend is a new service that allows AWS customers to analyze their unstructured text data by using Natural Language Processing (NLP). Customers can perform tasks like language detection (capable of detecting up to 100 languages), identify entities such as person, place and product (entity recognition), analyze if the sentiment is positive, negative or neutral (sentiment analysis), extract Keyphrases and extract topics from a corpus of documents.", arg = "https://console.aws.amazon.com/comprehend/v2/home"},
    makeItem { title = "Amazon Connect", subtitle = "Amazon Connect is a self-service, scalable, cloud-based contact center solution that enables dynamic, personal, and natural customer engagement.", arg = "https://console.aws.amazon.com/connect/home"},
    makeItem { title = "Amazon DocumentDB", subtitle = "Fast, reliable, and fully-managed MongoDB-compatible database service.", arg = "https://console.aws.amazon.com/docdb/home"},
    makeItem { title = "Amazon EventBridge", subtitle = "Amazon EventBridge is a serverless event bus that ingests and processes events from AWS services, SaaS, and your own applications in near real time.", arg = "https://console.aws.amazon.com/events/home"},
    makeItem { title = "Amazon Forecast", subtitle = "Amazon Forecast is a fully-managed time series forecasting service built on deep learning technology that can improve accuracy by up to 50% compared to traditional forecasting techniques.", arg = "https://console.aws.amazon.com/forecast/home"},
    makeItem { title = "Amazon Fraud Detector", subtitle = "Amazon Fraud Detector is a fraud detection service that makes it easy for you to use machine learning to detect more online fraud faster.", arg = "https://console.aws.amazon.com/frauddetector/home"},
    makeItem { title = "Amazon GameLift", subtitle = "Deploy and scale session-based multiplayer games in the cloud in minutes, with no upfront costs.", arg = "https://console.aws.amazon.com/gamelift/home"},
    makeItem { title = "Amazon Kendra", subtitle = "Amazon Kendra is a highly accurate and easy to use enterprise search service that’s powered by machine learning. Enterprise search; machine learning; AI; ML; search; unstructured data; connectors; natural language; search engine; incremental learning; accurate results; reading comprehension; FAQ;", arg = "https://console.aws.amazon.com/kendra/home"},
    makeItem { title = "Amazon Keyspaces", subtitle = "Scalable, highly available, and serverless Apache Cassandra-compatible database service.", arg = "https://console.aws.amazon.com/keyspaces/home"},
    makeItem { title = "Amazon Lex", subtitle = "Amazon Lex is a service for building conversational interfaces using voice and text, powered by Alexa.", arg = "https://console.aws.amazon.com/lex/home"},
    makeItem { title = "Amazon MQ", subtitle = "Amazon MQ is a managed message broker service for Apache ActiveMQ that makes it easy to set up and operate message brokers in the cloud.", arg = "https://console.aws.amazon.com/amazon-mq/home"},
    makeItem { title = "Amazon Machine Learning", subtitle = "Amazon Machine Learning is a service that enables you to easily build smart applications.", arg = "https://console.aws.amazon.com/machinelearning/home"},
    makeItem { title = "Amazon Macie", subtitle = "Amazon Macie, a visibility security service that helps classify and secure your sensitive and business-critical content.", arg = "https://console.aws.amazon.com/macie/home"},
    makeItem { title = "Amazon Managed Blockchain", subtitle = "Easily create and manage scalable blockchain networks with popular open source blockchain frameworks, Hyperledger Fabric and Ethereum", arg = "https://console.aws.amazon.com/managedblockchain/home"},
    makeItem { title = "Amazon Personalize", subtitle = "Amazon Personalize is a machine learning service that makes it easy for developers to add real-time personalization and recommendations to their apps.", arg = "https://console.aws.amazon.com/personalize/home"},
    makeItem { title = "Amazon Polly", subtitle = "Amazon Polly is a service that turns text into lifelike speech.", arg = "https://console.aws.amazon.com/polly/home"},
    makeItem { title = "Amazon QLDB", subtitle = "Fully managed ledger database that provides a transparent, immutable, and cryptographically verifiable transaction log.", arg = "https://console.aws.amazon.com/qldb/home"},
    makeItem { title = "Amazon Redshift", subtitle = "Amazon Redshift is a fast, fully managed, petabyte-scale data warehouse that makes it cost-effective to analyze all your data using your existing business intelligence tools.", arg = "https://console.aws.amazon.com/redshift/home"},
    makeItem { title = "Amazon Redshift", subtitle = "Amazon Redshift is a fast, fully managed, petabyte-scale data warehouse that makes it cost-effective to analyze all your data using your existing business intelligence tools.", arg = "https://console.aws.amazon.com/redshiftv2/home"},
    makeItem { title = "Amazon Rekognition", subtitle = "Amazon Rekognition is a deep learning-based image recognition service that enables you to search, verify, and organize millions of images.", arg = "https://console.aws.amazon.com/rekognition/home"},
    makeItem { title = "Amazon SageMaker", subtitle = "Amazon SageMaker is a fully-managed service that enables data scientists and developers to quickly and easily build, train, and deploy machine learning models at scale.", arg = "https://console.aws.amazon.com/sagemaker/home"},
    makeItem { title = "Amazon Sumerian", subtitle = "Amazon Sumerian, create and run virtual reality (VR), augmented reality (AR), and 3D applications", arg = "https://console.aws.amazon.com/sumerian/home"},
    makeItem { title = "Amazon Textract", subtitle = "Amazon Textract is a service that automatically extracts text and data from scanned documents. Amazon Textract goes beyond simple optical character recognition (OCR) to also identify the contents of fields in forms and information stored in tables.", arg = "https://console.aws.amazon.com/textract/home"},
    makeItem { title = "Amazon Transcribe", subtitle = "Amazon Transcribe is an automatic speech recognition (ASR) service that makes it easy for developers to add speech-to-text capability to their applications. Using the Amazon Transcribe API, you can analyze any audio files stored in a common format (WAV, MP3, etc.) in Amazon Simple Storage Service (S3) and have the service return a text file of all the transcribed speech.", arg = "https://console.aws.amazon.com/transcribe/home"},
    makeItem { title = "Amazon Translate", subtitle = "Powered by deep learning technology, Amazon Translate delivers fast, high-quality, and affordable language translation. The service offers a managed and easy to use solution for crossing the language barrier – enabling you to translate large volumes of text efficiently, and easily localize the applications you build for international use.", arg = "https://console.aws.amazon.com/translate/home"},
    makeItem { title = "AppStream 2.0", subtitle = "Amazon AppStream 2.0 allows you to stream desktop applications securely to any web browser.", arg = "https://console.aws.amazon.com/appstream2/home"},
    makeItem { title = "Application Discovery Service", subtitle = "AWS Application Discovery Service simplifies application migration planning by automatically identifying applications inventory and their associated dependencies.", arg = "https://console.aws.amazon.com/discovery/home"},
    makeItem { title = "Artifact", subtitle = "Access AWS compliance reports on-demand with AWS Artifact.", arg = "https://console.aws.amazon.com/artifact/home"},
    makeItem { title = "Athena", subtitle = "Amazon Athena is an interactive query service that makes it easy to analyze data in Amazon S3, using standard SQL.", arg = "https://console.aws.amazon.com/athena/home"},
    makeItem { title = "Batch", subtitle = "AWS Batch enables developers, scientists, and engineers to easily and efficiently run hundreds of thousands of batch computing jobs on AWS.", arg = "https://console.aws.amazon.com/batch/home"},
    makeItem { title = "Billing", subtitle = "Access, analyze, and control your AWS costs and usage.", arg = "https://console.aws.amazon.com/billing/home"},
    makeItem { title = "Certificate Manager", subtitle = "AWS Certificate Manager lets you easily provision, manage, and deploy Secure Sockets Layer/Transport Layer Security (SSL/TLS) certificates for use with AWS services.", arg = "https://console.aws.amazon.com/acm/home"},
    makeItem { title = "Cloud9", subtitle = "A cloud IDE (Integrated Development Environment) for writing, running, and debugging code.", arg = "https://console.aws.amazon.com/cloud9/home"},
    makeItem { title = "CloudFormation", subtitle = "AWS CloudFormation lets you create and update a collection of related AWS resources in a predictable fashion.", arg = "https://console.aws.amazon.com/cloudformation/home"},
    makeItem { title = "CloudFront", subtitle = "Amazon CloudFront provides a way to distribute content to end users with low latency and high data transfer speeds.", arg = "https://console.aws.amazon.com/cloudfront/home"},
    makeItem { title = "CloudHSM", subtitle = "CloudHSM provides fully-managed FIPS 140-2 Level 3 Hardware Security Modules (HSMs) in the cloud to create, store, manage, and use the cryptographic keys used to protect sensitive data.", arg = "https://console.aws.amazon.com/cloudhsm/home"},
    makeItem { title = "CloudSearch", subtitle = "AWS CloudSearch is a fully managed search service for websites and apps.", arg = "https://console.aws.amazon.com/cloudsearch/home"},
    makeItem { title = "CloudTrail", subtitle = "AWS CloudTrail provides increased visibility into user activity by recording API calls made on your account.", arg = "https://console.aws.amazon.com/cloudtrail/home"},
    makeItem { title = "CloudWatch Dashboards", subtitle = "", arg = "https://console.aws.amazon.com/cloudwatch/home#dashboards:" },
    makeItem { title = "CloudWatch Events Rules", subtitle = "", arg = "https://console.aws.amazon.com/cloudwatch/home?#rules:"},
    makeItem { title = "CloudWatch Logs", subtitle = "", arg = "https://console.aws.amazon.com/cloudwatch/home#logs:"},
    makeItem { title = "CloudWatch Metrics", subtitle = "", arg = "https://console.aws.amazon.com/cloudwatch/home?#metricsV2:"},
    makeItem { title = "CloudWatch", subtitle = "Amazon CloudWatch provides monitoring and metrics for resources and applications.", arg = "https://console.aws.amazon.com/cloudwatch/home"},
    makeItem { title = "CodeBuild", subtitle = "AWS CodeBuild is a build service that compiles source code and runs unit tests.", arg = "https://console.aws.amazon.com/codesuite/codebuild/home"},
    makeItem { title = "CodeCommit", subtitle = "AWS CodeCommit is a highly scalable, managed source control service that hosts private Git repositories.", arg = "https://console.aws.amazon.com/codesuite/codecommit/home"},
    makeItem { title = "CodeDeploy", subtitle = "AWS CodeDeploy lets you fully automate code deployments.", arg = "https://console.aws.amazon.com/codesuite/codedeploy/home"},
    makeItem { title = "CodePipeline", subtitle = "AWS CodePipeline is a continuous delivery service that enables you to model, visualize, and automate the steps required to release your software.", arg = "https://console.aws.amazon.com/codesuite/codepipeline/home"},
    makeItem { title = "CodeStar", subtitle = "Everything you need to quickly develop, build, and deploy applications.", arg = "https://console.aws.amazon.com/codestar/home"},
    makeItem { title = "Cognito", subtitle = "Amazon Cognito is a simple user identity and data synchronization service that helps you securely manage and synchronize app data for your users across their mobile devices.", arg = "https://console.aws.amazon.com/cognito/home"},
    makeItem { title = "Config Rules", subtitle = "", arg = "https://console.aws.amazon.com/configrules/home"},
    makeItem { title = "Config", subtitle = "AWS Config gives you inventory of your AWS resources, lets you audit resource configuration history, and notifies you when resource configurations change.", arg = "https://console.aws.amazon.com/config/home"},
    makeItem { title = "Console Home", subtitle = "The default landing page for the AWS Management Console", arg = "https://console.aws.amazon.com/console/home"},
    makeItem { title = "Control Tower", subtitle = "AWS Control Tower provides you with a single location to set up a well architected multi-account environment to govern your AWS workloads with rules for security, operations, and compliance.", arg = "https://console.aws.amazon.com/controltower/home"},
    makeItem { title = "Data Pipeline", subtitle = "AWS Data Pipeline is a lightweight orchestration service for periodic, data-driven workflows.", arg = "https://console.aws.amazon.com/datapipeline/home"},
    makeItem { title = "DataSync", subtitle = "DataSync simplifies, automates, and accelerates moving and replicating data between on-premises storage and AWS services over the network.", arg = "https://console.aws.amazon.com/datasync/home"},
    makeItem { title = "Database Migration Service", subtitle = "AWS Database Migration Service (DMS) helps you migrate databases to the cloud easily and securely while minimizing downtime.", arg = "https://console.aws.amazon.com/dms/v2/home"},
    makeItem { title = "Detective", subtitle = "Analyze and visualize security data to rapidly get to the root cause of potential security issues", arg = "https://console.aws.amazon.com/detective/home"},
    makeItem { title = "Device Farm", subtitle = "AWS Device Farm helps you improve the quality of your Android, iOS and web apps through automated and manual testing on real devices in the AWS Cloud.", arg = "https://console.aws.amazon.com/devicefarm/home"},
    makeItem { title = "Direct Connect", subtitle = "AWS Direct Connect lets you establish a dedicated network connection from your network to AWS.", arg = "https://console.aws.amazon.com/directconnect/home"},
    makeItem { title = "Direct Connect", subtitle = "AWS Direct Connect lets you establish a dedicated network connection from your network to AWS.", arg = "https://console.aws.amazon.com/directconnect/v2/home"},
    makeItem { title = "Directory Service", subtitle = "AWS Directory Service provides managed directories in the cloud.", arg = "https://console.aws.amazon.com/directoryservicev2/home"},
    makeItem { title = "DynamoDB", subtitle = "Amazon DynamoDB is a scalable NoSQL data store that manages distributed replicas of your data for high availability.", arg = "https://console.aws.amazon.com/dynamodb/home"},
    makeItem { title = "EC2 AutoScalingGroups", subtitle = "", arg = "https://console.aws.amazon.com/ec2/autoscaling/home?#AutoScalingGroups:view=details"},
    makeItem { title = "EC2 Image Builder", subtitle = "EC2 Image Builder is a managed service that makes it easier and faster to build customized OS images for use on AWS and on-premises.", arg = "https://console.aws.amazon.com/imagebuilder/home"},
    makeItem { title = "EC2 Instances", subtitle = "EC2 Instances", arg = "https://console.aws.amazon.com/ec2/#Instances"},
    makeItem { title = "EC2 LaunchConfugurations", subtitle = "", arg = "https://console.aws.amazon.com/ec2/autoscaling/home?#LaunchConfigurations:"},
    makeItem { title = "EC2 Spot", subtitle = "", arg = "https://console.aws.amazon.com/ec2spot/home"},
    makeItem { title = "EC2", subtitle = "Amazon Elastic Compute Cloud (EC2) provides resizable compute capacity through virtual machines (VM&apos;s or instances) in the cloud.", arg = "https://console.aws.amazon.com/ec2/v2/home"},
    makeItem { title = "EFS", subtitle = "Amazon EFS stores and retrieves file data for Amazon EC2 instances.", arg = "https://console.aws.amazon.com/efs/home"},
    makeItem { title = "ELB LoadBalancers", subtitle = "", arg = "https://console.aws.amazon.com/ec2/v2/home?#LoadBalancers:sort=loadBalancerName"},
    makeItem { title = "ELB TargetGroups", subtitle = "", arg = "https://console.aws.amazon.com/ec2/v2/home?#TargetGroups:sort=targetGroupName"},
    makeItem { title = "EMR", subtitle = "Amazon Elastic MapReduce lets you perform big data tasks such as web indexing, data mining, and log file analysis.", arg = "https://console.aws.amazon.com/elasticmapreduce/home"},
    makeItem { title = "ElastiCache Dashboard", subtitle = "", arg = "https://console.aws.amazon.com/elasticache/home?#"},
    makeItem { title = "ElastiCache", subtitle = "Amazon ElastiCache improves application performance by allowing you to retrieve information from an in-memory caching system.", arg = "https://console.aws.amazon.com/elasticache/home"},
    makeItem { title = "Elastic Beanstalk", subtitle = "AWS Elastic Beanstalk is an application container for deploying and managing applications.", arg = "https://console.aws.amazon.com/elasticbeanstalk/home"},
    makeItem { title = "Elastic Container Registry - ECR", subtitle = "Amazon Elastic Container Registry (ECR) is a fully-managed Docker container registry that makes it easy for developers to store, manage, and deploy Docker container images.", arg = "https://console.aws.amazon.com/ecr/home"},
    makeItem { title = "Elastic Container Service - ECS", subtitle = "Amazon ECS allows you to easily run and manage Docker containers across a cluster of Amazon EC2 instances.", arg = "https://console.aws.amazon.com/ecs/home"},
    makeItem { title = "Elastic Container Service Clusters - ECS", subtitle = "", arg = "https://console.aws.amazon.com/ecs/home?#/clusters"},
    makeItem { title = "Elastic Container Service TaskDefinition - ECS", subtitle = "", arg = "https://console.aws.amazon.com/ecs/home#/taskDefinitions"},
    makeItem { title = "Elastic Kubernetes Service - EKS", subtitle = "Amazon EKS makes it easy to run containers with Kubernetes on AWS by provisioning and managing the Kubernetes control plane for you.", arg = "https://console.aws.amazon.com/eks/home"},
    makeItem { title = "Elastic Kubernetes Service Clusters - EKS", subtitle = "", arg = "https://console.aws.amazon.com/eks/home#/clusters"},
    makeItem { title = "Elastic Transcoder", subtitle = "Amazon Elastic Transcoder lets you convert your media files in the cloud easily, at low cost, and at scale.", arg = "https://console.aws.amazon.com/elastictranscoder/home"},
    makeItem { title = "Elasticsearch Service", subtitle = "Amazon Elasticsearch Service is a managed service that makes it easy to deploy, operate, and scale Elasticsearch, a popular open-source search and analytics engine.", arg = "https://console.aws.amazon.com/es/home"},
    makeItem { title = "Elasticsearch", subtitle = "", arg = "https://console.aws.amazon.com/es/home"},
    makeItem { title = "Elemental Appliances & Software", subtitle = "On-premises solutions for video processing and delivery", arg = "https://console.aws.amazon.com/elemental-appliances-software/home"},
    makeItem { title = "FSx", subtitle = "Amazon FSx provides fully-managed third-party file systems optimized for a variety of enterprise and compute-intensive workloads.", arg = "https://console.aws.amazon.com/fsx/home"},
    makeItem { title = "FreeRTOS", subtitle = "FreeRTOS is an operating system for microcontrollers that makes it easy to securely connect IoT devices locally or to the cloud.", arg = "https://console.aws.amazon.com/freertos/home"},
    makeItem { title = "Global Accelerator", subtitle = "Ubiquity is a traffic manager that helps you improve the availability and performance of your internet applications for your global customers", arg = "https://console.aws.amazon.comhttps://us-west-2.console.aws.amazon.com/ec2/GlobalAccelerator/home?region=us-west-2"},
    makeItem { title = "Ground Station", subtitle = "AWS Ground Station makes it easy to downlink data and command and control satellites using fully managed, self-service ground station antennas.", arg = "https://console.aws.amazon.com/groundstation/home"},
    makeItem { title = "GuardDuty", subtitle = "Managed threat detection service to continuously monitor and protect your AWS accounts and the applications and services running within them.", arg = "https://console.aws.amazon.com/guardduty/home"},
    makeItem { title = "IAM Roles", subtitle = "", arg = "https://console.aws.amazon.com/iam/home?#/roles"},
    makeItem { title = "IAM", subtitle = "AWS Identity and Access Management (IAM) lets you securely control access to AWS services and resources.", arg = "https://console.aws.amazon.com/iam/home"},
    makeItem { title = "Inspector", subtitle = "Amazon Inspector enables you to analyze the behavior of the applications you run in AWS and helps you to identify potential security issues.", arg = "https://console.aws.amazon.com/inspector/home"},
    makeItem { title = "IoT 1-Click", subtitle = "AWS IoT 1-Click supported devices trigger AWS Lambda functions to execute an action, provide built-in secure connectivity, and can be easily managed.", arg = "https://console.aws.amazon.com/iot1click/home"},
    makeItem { title = "IoT Analytics", subtitle = "AWS IoT Analytics lets you collect, process, store, analyze and visualize data of IoT devices at scale to gain actionable insights.", arg = "https://console.aws.amazon.com/iotanalytics/home"},
    makeItem { title = "IoT Core", subtitle = "AWS IoT is a managed cloud service that lets connected devices easily and securely interact with cloud applications and other devices.", arg = "https://console.aws.amazon.com/iot/home"},
    makeItem { title = "IoT Device Defender", subtitle = "AWS IoT is a managed cloud service that lets connected devices easily and securely interact with cloud applications and other devices.", arg = "https://console.aws.amazon.com/devicedefender/home"},
    makeItem { title = "IoT Device Management", subtitle = "AWS IoT Device Management lets you securely onboard, organize, monitor, and remotely manage your IoT devices at scale.", arg = "https://console.aws.amazon.com/iotdm/home"},
    makeItem { title = "IoT Events", subtitle = "Monitor device fleets, identify issues across multiple sensors, and take appropriate action when events are detected before loss or waste occurs", arg = "https://console.aws.amazon.com/iotevents/home"},
    makeItem { title = "IoT Greengrass", subtitle = "AWS Greengrass extends AWS onto your devices, so they can act locally on the data they generate, while still taking advantage of the cloud.", arg = "https://console.aws.amazon.com/greengrass/home"},
    makeItem { title = "IoT SiteWise", subtitle = "AWS IoT SiteWise is a digital transformation service that makes it easy and cost effective to put operators in charge of the data they use most.", arg = "https://console.aws.amazon.com/iotsitewise/home"},
    makeItem { title = "IoT Things Graph", subtitle = "ThingsGraph lets you easily build IoT applications by connecting devices and web services with little to no code.", arg = "https://console.aws.amazon.com/thingsgraph/home"},
    makeItem { title = "Key Management Service", subtitle = "Centralized Generation and Management of Encryption Keys to Control Access to Stored Data Across AWS.", arg = "https://console.aws.amazon.com/kms/home"},
    makeItem { title = "Kinesis Analytics", subtitle = "", arg = "https://console.aws.amazon.com/kinesisanalytics/home"},
    makeItem { title = "Kinesis Firehose", subtitle = "", arg = "https://console.aws.amazon.com/firehose/home"},
    makeItem { title = "Kinesis Video Streams", subtitle = "Capture, process, and store video streams for analytics and machine learning.", arg = "https://console.aws.amazon.com/kinesisvideo/home"},
    makeItem { title = "Kinesis", subtitle = "Amazon Kinesis services make it easy to work with real-time streaming data in the AWS cloud.", arg = "https://console.aws.amazon.com/kinesis/home"},
    makeItem { title = "Lambda Applications", subtitle = "", arg = "https://console.aws.amazon.com/lambda/home?#/applications"},
    makeItem { title = "Lambda Functions", subtitle = "", arg = "https://console.aws.amazon.com/lambda/home?#/functions"},
    makeItem { title = "Lambda Layers", subtitle = "", arg = "https://console.aws.amazon.com/lambda/home?#/layers"},
    makeItem { title = "Lambda", subtitle = "AWS Lambda is a compute service that runs your code in response to events and automatically manages the compute resources for you.", arg = "https://console.aws.amazon.com/lambda/home"},
    makeItem { title = "Launch Wizard", subtitle = "AWS Launch Wizard guides you through sizing, configuring, and deploying third party applications on AWS without you having to identify and provision individual AWS resources.", arg = "https://console.aws.amazon.com/launchwizard/home"},
    makeItem { title = "Lightsail", subtitle = "Amazon Lightsail is the easiest way to run virtual private servers on AWS and offers predictable pricing starting at $5 per month.", arg = "https://console.aws.amazon.comhttps://lightsail.aws.amazon.com/ls/webapp/home"},
    makeItem { title = "MSK", subtitle = "Amazon Managed Streaming for Kafka makes it easy for you to migrate, build, and run real-team streaming applications on Apache Kafka by managing Kafka&apos;s cluster infrastructure for you.", arg = "https://console.aws.amazon.com/msk/home"},
    makeItem { title = "Managed Services", subtitle = "AWS MS provides infrastructure operations and IT management processes for enterprises running AWS.", arg = "https://console.aws.amazon.com/managedservices/home"},
    makeItem { title = "MediaConnect", subtitle = "AWS Elemental MediaConnect is a reliable, secure, and flexible live video transport service for high-quality contribution and global sharing.", arg = "https://console.aws.amazon.com/mediaconnect/home"},
    makeItem { title = "MediaConvert", subtitle = "AWS Elemental MediaConvert is a file-based video conversion service that transforms media into formats required by broadcast and multiscreen devices", arg = "https://console.aws.amazon.com/mediaconvert/home"},
    makeItem { title = "MediaLive", subtitle = "AWS Elemental MediaLive is a video service that allows easy and reliable creation of live outputs for broadcast and streaming delivery", arg = "https://console.aws.amazon.com/medialive/home"},
    makeItem { title = "MediaPackage", subtitle = "AWS Elemental MediaPackage is a format conversion service that delivers live and on-demand video to many devices from a single source", arg = "https://console.aws.amazon.com/mediapackage/home"},
    makeItem { title = "MediaStore", subtitle = "AWS Elemental MediaStore is an AWS storage service optimized for media. It gives you the performance, consistency, and low latency required to deliver live and on-demand video content at scale.", arg = "https://console.aws.amazon.com/mediastore/home"},
    makeItem { title = "MediaTailor", subtitle = "AWS Elemental MediaTailor is a content personalization and monetization service that allows video providers to serve content with targeted advertising", arg = "https://console.aws.amazon.com/mediatailor/home"},
    makeItem { title = "Mobile Hub", subtitle = "AWS Mobile Hub lets you quickly build, test, and monitor usage of your mobile apps.", arg = "https://console.aws.amazon.com/mobilehub/home"},
    makeItem { title = "Neptune", subtitle = "Amazon Neptune is a fast, reliable, fully-managed graph database service that makes it easy to build and run applications that work with highly connected datasets.", arg = "https://console.aws.amazon.com/neptune/home"},
    makeItem { title = "Network Manager", subtitle = "", arg = "https://console.aws.amazon.com/networkmanager/home"},
    makeItem { title = "OpsWorks", subtitle = "AWS OpsWorks helps you automate configuration management tasks with Chef.", arg = "https://console.aws.amazon.com/opsworks/landing/home"},
    makeItem { title = "Personal Health Dashboard", subtitle = "Personalized view of AWS service health.", arg = "https://console.aws.amazon.comhttps://phd.aws.amazon.com/phd/home"},
    makeItem { title = "PersonalHealthDashboard", subtitle = "", arg = "https://phd.aws.amazon.com/phd/home"},
    makeItem { title = "Pinpoint", subtitle = "Amazon Pinpoint makes it easy to run targeted campaigns to improve user engagement.", arg = "https://console.aws.amazon.com/pinpoint/home"},
    makeItem { title = "QuickSight", subtitle = "Amazon QuickSight is a fast, business analytics service at 1/10ᵗʰ the cost of traditional BI solutions.", arg = "https://console.aws.amazon.comhttps://quicksight.aws.amazon.com"},
    makeItem { title = "RDS databases", subtitle = "", arg = "https://console.aws.amazon.com/rds/home#databases:"},
    makeItem { title = "RDS", subtitle = "Amazon Relational Database Service (RDS) makes it easy to set up, operate, and scale relational databases in the cloud, such as MySQL, Aurora, MariaDB, and Oracle.", arg = "https://console.aws.amazon.com/rds/home"},
    makeItem { title = "RDS", subtitle = "RDS Dashboard", arg = "https://console.aws.amazon.com/rds/home"},
    makeItem { title = "Resource Access Manager", subtitle = "AWS Resource Access Manager (RAM) enables you to easily and securely share AWS resources with any AWS account, or within your AWS Organization", arg = "https://console.aws.amazon.com/ram/home"},
    makeItem { title = "Resource Groups", subtitle = "AWS Resource Groups lets you organize your AWS resources. Includes Tag Editor to manage tags.", arg = "https://console.aws.amazon.com/resource-groups/home"},
    makeItem { title = "Route 53 Hosted zones", subtitle = "", arg = "https://console.aws.amazon.com/route53/home#hosted-zones:"},
    makeItem { title = "Route 53 Resolver", subtitle = "Route 53 Resolver provides recursive DNS for your Amazon VPC and on-premises networks over VPN or Direct Connect.", arg = "https://console.aws.amazon.com/route53resolver/home"},
    makeItem { title = "Route 53", subtitle = "Amazon Route 53 is a scalable and highly available Domain Name System (DNS) and Domain Name Registration service.", arg = "https://console.aws.amazon.com/route53/home"},
    makeItem { title = "S3 Glacier", subtitle = "Amazon Glacier is a low-cost storage service that provides secure and durable storage for data archiving and backup.", arg = "https://console.aws.amazon.com/glacier/home"},
    makeItem { title = "S3", subtitle = "Amazon Simple Storage Service (S3) provides easy-to-use object storage to store and retrieve any amount of data in the cloud.", arg = "https://console.aws.amazon.com/s3/home"},
    makeItem { title = "SNS Dashboard", subtitle = "", arg = "https://console.aws.amazon.com/sns/v3/home?#/dashboard"},
    makeItem { title = "SNS Topics", subtitle = "", arg = "https://console.aws.amazon.com/sns/v3/home#/topics"},
    makeItem { title = "SSM Managed Instances", subtitle = "", arg = "https://console.aws.amazon.com/systems-manager/managed-instances"},
    makeItem { title = "SWF", subtitle = "Amazon Simple Workflow (SWF) coordinates all of the processing steps within an application.", arg = "https://console.aws.amazon.com/swf/home"},
    makeItem { title = "Secrets Manager", subtitle = "Easily rotate, manage, and retrieve database credentials, API keys, and other secrets through their lifecycle.", arg = "https://console.aws.amazon.com/secretsmanager/home"},
    makeItem { title = "Security Hub", subtitle = "AWS Security Hub is a security and compliance center that correlates AWS security findings and performs automated compliance checks.", arg = "https://console.aws.amazon.com/securityhub/home"},
    makeItem { title = "Server Migration Service", subtitle = "AWS Server Migration Service makes it easier and faster for you to migrate on-premises servers to AWS by automating the replication of live server volumes incrementally.", arg = "https://console.aws.amazon.com/servermigration/home"},
    makeItem { title = "Serverless Application Repository", subtitle = "Discover and deploy serverless applications or publish and share applications, publicly or privately.", arg = "https://console.aws.amazon.com/serverlessrepo/home"},
    makeItem { title = "Service Catalog", subtitle = "AWS Service Catalog allows organizations to manage approved catalogs of IT resources and make them available to employees via a personalized portal.", arg = "https://console.aws.amazon.com/catalog/home"},
    makeItem { title = "Service Catalog", subtitle = "AWS Service Catalog allows organizations to manage approved catalogs of IT resources and make them available to employees via a personalized portal.", arg = "https://console.aws.amazon.com/servicecatalog/home"},
    makeItem { title = "Service Quotas", subtitle = "View and manage your AWS service quotas from a central location", arg = "https://console.aws.amazon.com/servicequotas/home"},
    makeItem { title = "Simple Email Service", subtitle = "Amazon Simple Email Service (SES) enables you to send and receive email.", arg = "https://console.aws.amazon.com/ses/home"},
    makeItem { title = "Simple Notification Service", subtitle = "Amazon Simple Notification Service (SNS) lets you publish messages to subscribers or other applications.", arg = "https://console.aws.amazon.com/sns/home"},
    makeItem { title = "Simple Queue Service", subtitle = "Amazon Simple Queue Service (SQS) offers a reliable, highly scalable, hosted queue for storing messages.", arg = "https://console.aws.amazon.com/sqs/home"},
    makeItem { title = "Snowball", subtitle = "AWS Snowball accelerates moving large amounts of data into and out of AWS using secure appliances for transport.", arg = "https://console.aws.amazon.com/importexport/home"},
    makeItem { title = "Step Functions", subtitle = "AWS Step Functions makes it easy to coordinate the components of distributed applications using visual workflows.", arg = "https://console.aws.amazon.com/states/home"},
    makeItem { title = "Storage Gateway", subtitle = "AWS Storage Gateway securely integrates on-premises IT environments with cloud storage for backup and disaster recovery.", arg = "https://console.aws.amazon.com/storagegateway/home"},
    makeItem { title = "Support", subtitle = "Contact AWS for technical and account support.", arg = "https://console.aws.amazon.com/support"},
    makeItem { title = "Synthetics", subtitle = "", arg = "https://console.aws.amazon.com/synthetics/home"},
    makeItem { title = "Systems Manager", subtitle = "AWS Systems Manager is a unified interface that centralizes operational data from multiple AWS services and automates tasks across AWS resources.", arg = "https://console.aws.amazon.com/systems-manager/home"},
    makeItem { title = "Trusted Advisor", subtitle = "AWS Trusted Advisor inspects your AWS environment and finds opportunities to save money, improve system performance and reliability, or help close security gaps.", arg = "https://console.aws.amazon.com/trustedadvisor/home"},
    makeItem { title = "VPC Dashboard", subtitle = "", arg = "https://console.aws.amazon.com/vpc/home?#"},
    makeItem { title = "VPC SecurityGroups", subtitle = "", arg = "https://console.aws.amazon.com/vpc/home?#SecurityGroups:sort=tag:Name"},
    makeItem { title = "VPC Subnets", subtitle = "", arg = "https://console.aws.amazon.com/vpc/home#subnets:sort=tag:Name"},
    makeItem { title = "VPC", subtitle = "Amazon Virtual Private Cloud (VPC) lets you launch AWS resources in a private, isolated cloud.", arg = "https://console.aws.amazon.com/vpc/home#vpcs:sort=VpcId"},
    makeItem { title = "WAF & Shield", subtitle = "AWS WAF (Web Application Firewall) protects web applications from attack by providing web traffic filtering against common web exploits like SQL injection.", arg = "https://console.aws.amazon.com/waf/home"},
    makeItem { title = "WAF & Shield v2", subtitle = "AWS WAF (Web Application Firewall) protects web applications from attack by providing web traffic filtering against common web exploits like SQL injection.", arg = "https://console.aws.amazon.com/wafv2/home"},
    makeItem { title = "WorkDocs", subtitle = "Amazon WorkDocs is a fully managed, secure enterprise storage and sharing service with strong administrative controls and feedback capabilities that improve user productivity.", arg = "https://console.aws.amazon.com/zocalo/home"},
    makeItem { title = "WorkLink", subtitle = "Enable secure one-click access to internal websites and web apps from mobile phones.", arg = "https://console.aws.amazon.com/worklink/home"},
    makeItem { title = "WorkMail", subtitle = "Amazon WorkMail is a managed email and calendaring service that offers strong security controls and support for existing desktop and mobile clients.", arg = "https://console.aws.amazon.com/workmail/home"},
    makeItem { title = "WorkSpaces Application Manager", subtitle = "[Placeholder text about WAM]", arg = "https://console.aws.amazon.com/wam/home"},
    makeItem { title = "WorkSpaces", subtitle = "Amazon WorkSpaces is a fully managed desktop computing service in the cloud.", arg = "https://console.aws.amazon.com/workspaces/home"},
    makeItem { title = "X-Ray", subtitle = "AWS X-Ray helps developers analyze and debug production, distributed applications.", arg = "https://console.aws.amazon.com/xray/home"}
  ]

let regions : List Item =
  [
    makeItem { title = "US East - N. Virginia", subtitle = "us-east-1", arg = "us-east-1" },
    makeItem { title = "US East - Ohio", subtitle = "us-east-2", arg = "us-east-2" },
    makeItem { title = "US West - N. California", subtitle = "us-west-1", arg = "us-west-1" },
    makeItem { title = "US West - Oregon", subtitle = "us-west-2", arg = "us-west-2" },
    makeItem { title = "Africa - Cape Town", subtitle = "af-south-1", arg = "af-south-1" },
    makeItem { title = "Asia Pacific - Hong Kong", subtitle = "ap-east-1", arg = "ap-east-1" },
    makeItem { title = "Asia Pacific - Mumbai", subtitle = "ap-south-1", arg = "ap-south-1" },
    makeItem { title = "Asia Pacific - Seoul", subtitle = "ap-northeast-2", arg = "ap-northeast-2" },
    makeItem { title = "Asia Pacific - Singapore", subtitle = "ap-southeast-1", arg = "ap-southeast-1" },
    makeItem { title = "Asia Pacific - Sydney", subtitle = "ap-southeast-2", arg = "ap-southeast-2" },
    makeItem { title = "Asia Pacific - Tokyo", subtitle = "ap-northeast-1", arg = "ap-northeast-1" },
    makeItem { title = "Canada - Central", subtitle = "ca-central-1", arg = "ca-central-1" },
    makeItem { title = "Europe - Frankfurt", subtitle = "eu-central-1", arg = "eu-central-1" },
    makeItem { title = "Europe - Ireland", subtitle = "eu-west-1", arg = "eu-west-1" },
    makeItem { title = "Europe - London", subtitle = "eu-west-2", arg = "eu-west-2" },
    makeItem { title = "Europe - Milan", subtitle = "eu-south-1", arg = "eu-south-1" },
    makeItem { title = "Europe - Paris", subtitle = "eu-west-3", arg = "eu-west-3" },
    makeItem { title = "Europe - Stockholm", subtitle = "eu-north-1", arg = "eu-north-1" },
    makeItem { title = "Middle East - Bahrain", subtitle = "me-south-1", arg = "me-south-1" },
    makeItem { title = "South America - São Paulo", subtitle = "sa-east-1", arg = "sa-east-1" }
  ]

in {
  services = services,
  regions = regions
}
