on:
  create:
    tags:
    - v*.*.*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run:  zip -r -X "./aws-console.alfredworkflow" . -x ".github" -x ".git" -x "Makefile" -x "items.dhall"
      - name: Release
        uses: actions/upload-artifact@v2
        with:
          name: aws-console.alfredworkflow
          path: ./aws-console.alfredworkflow
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
